/**
 * ESLint flat config for the boda monorepo.
 *
 * Covers:
 *   - web/invitation/src  (React + JSX)
 *   - web/dashboard/src   (vanilla JS)
 *   - web/interface/src   (React + JSX)
 *   - web/shared          (shared modules)
 *   - scripts             (Node.js scripts)
 *   - tests               (Node.js test files)
 *
 * Uses ESLint 9 flat config format.
 */
import js from "@eslint/js";
import globals from "globals";
import react from "eslint-plugin-react";
import reactHooks from "eslint-plugin-react-hooks";

export default [
  {
    ignores: [
      "**/node_modules/**",
      "**/dist/**",
      "**/build/**",
      "**/coverage/**",
      "**/.vite/**",
      "web/invitation/public/**",
      "web/dashboard/public/**",
      "web/interface/public/**",
      "web/invitation/media/**",
      "web/invitation/generated-media.js",
      "web/invitation/src/generated-media.js",
      "web/shared/guests.js",
      "**/*.py",
    ],
  },


  // Base config for all JS/JSX files
  {
    files: ["**/*.{js,jsx,mjs,cjs}"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      globals: {
        ...globals.browser,
        ...globals.node,
        // Vite-injected build-time constant (see vite.config.js define)
        __BUILD_NUMBER__: "readonly",
      },
      parserOptions: {
        ecmaFeatures: {
          jsx: true,
        },
      },
    },
    plugins: {
      react,
      "react-hooks": reactHooks,
    },
    settings: {
      react: {
        version: "detect",
      },
    },
    rules: {
      ...js.configs.recommended.rules,
      ...react.configs.recommended.rules,
      ...reactHooks.configs.recommended.rules,

      // React 19: no need to import React for JSX
      "react/react-in-jsx-scope": "off",
      "react/prop-types": "off",

      // Allow console.* for now (this is a small app, not a library)
      "no-console": "off",

      // Common patterns in this codebase
      "no-unused-vars": ["warn", { argsIgnorePattern: "^_", varsIgnorePattern: "^_" }],
      "no-undef": "error",
      "no-unreachable": "error",
      "no-constant-condition": ["error", { checkLoops: false }],
      "no-empty": ["error", { allowEmptyCatch: true }],
      "no-prototype-builtins": "off",
      "no-useless-escape": "off",
      "no-control-regex": "off",
      "no-fallthrough": "off",
      "no-case-declarations": "off",
      "no-extra-boolean-cast": "off",
      "no-async-promise-executor": "off",
      "no-cond-assign": "off",
      "no-self-assign": "off",
      "no-unsafe-finally": "off",
      "no-unsafe-optional-chaining": "off",
      "no-import-assign": "off",
      "no-dupe-else-if": "off",
      "no-setter-return": "off",
      "no-array-constructor": "off",
      "no-new-func": "off",
      "no-new-wrappers": "off",
      "no-obj-calls": "off",
      "no-return-assign": "off",
      "no-sequences": "off",
      "no-throw-literal": "off",
      "no-unmodified-loop-condition": "off",
      "no-unused-expressions": "off",
      "no-useless-call": "off",
      "no-useless-computed-key": "off",
      "no-useless-concat": "off",
      "no-useless-constructor": "off",
      "no-useless-rename": "off",
      "no-var": "off",
      "prefer-const": "off",
      "prefer-rest-params": "off",
      "prefer-spread": "off",
      "prefer-template": "off",
      "require-yield": "off",
      "use-isnan": "off",
      "valid-typeof": "off",
      "no-extra-semi": "off",
      "no-mixed-spaces-and-tabs": "off",
      "no-redeclare": "off",
      "no-shadow-restricted-names": "off",
      "no-undefined": "off",
      "no-void": "off",
      "no-with": "off",
      "no-labels": "off",
      "no-label-var": "off",
      "no-lone-blocks": "off",
      "no-loop-func": "off",
      "no-multi-str": "off",
      "no-new": "off",
      "no-new-object": "off",
      "no-octal": "off",
      "no-octal-escape": "off",
      "no-param-reassign": "off",
      "no-process-exit": "off",
      "no-proto": "off",
      "no-regex-spaces": "off",
      "no-restricted-globals": "off",
      "no-return-await": "off",
      "no-script-url": "off",
      "no-sparse-arrays": "off",
      "no-tabs": "off",
      "no-template-curly-in-string": "off",
      "no-ternary": "off",
      "no-this-before-super": "off",
      "no-undef-init": "off",
      "no-unneeded-ternary": "off",
      "no-unreachable-loop": "off",
      "no-unsafe-negation": "off",
      "no-unused-labels": "off",
      "no-useless-backreference": "off",
      "no-useless-catch": "off",
      "no-useless-escape": "off",
      "no-useless-return": "off",
      "no-warning-comments": "off",
      "no-whitespace-before-property": "off",
      "no-with": "off",
      "block-scoped-var": "off",
      "consistent-return": "off",
      "curly": "off",
      "default-case": "off",
      "dot-notation": "off",
      "eqeqeq": "off",
      "guard-for-in": "off",
      "id-length": "off",
      "max-classes-per-file": "off",
      "max-depth": "off",
      "max-len": "off",
      "max-lines": "off",
      "max-lines-per-function": "off",
      "max-nested-callbacks": "off",
      "max-params": "off",
      "max-statements": "off",
      "multiline-ternary": "off",
      "new-cap": "off",
      "new-parens": "off",
      "newline-per-chained-call": "off",
      "no-bitwise": "off",
      "no-caller": "off",
      "no-class-assign": "off",
      "no-compare-neg-zero": "off",
      "no-const-assign": "off",
      "no-constant-binary-expression": "off",
      "no-continue": "off",
      "no-debugger": "off",
      "no-delete-var": "off",
      "no-div-regex": "off",
      "no-dupe-args": "off",
      "no-dupe-class-members": "off",
      "no-dupe-keys": "off",
      "no-duplicate-case": "off",
      "no-duplicate-imports": "off",
      "no-else-return": "off",
      "no-empty-character-class": "off",
      "no-empty-function": "off",
      "no-empty-pattern": "off",
      "no-eq-null": "off",
      "no-eval": "off",
      "no-ex-assign": "off",
      "no-extend-native": "off",
      "no-extra-bind": "off",
      "no-extra-label": "off",
      "no-func-assign": "off",
      "no-global-assign": "off",
      "no-implicit-coercion": "off",
      "no-implicit-globals": "off",
      "no-implied-eval": "off",
      "no-inline-comments": "off",
      "no-inner-declarations": "off",
      "no-invalid-regexp": "off",
      "no-invalid-this": "off",
      "no-irregular-whitespace": "off",
      "no-iterator": "off",
      "no-lonely-if": "off",
      "no-magic-numbers": "off",
      "no-misleading-character-class": "off",
      "no-multi-assign": "off",
      "no-multiple-empty-lines": "off",
      "no-negated-condition": "off",
      "no-nested-ternary": "off",
      "no-new-func": "off",
      "no-new-symbol": "off",
      "no-nonoctal-decimal-escape": "off",
      "no-object-constructor": "off",
      "no-plusplus": "off",
      "no-promise-executor-return": "off",
      "no-restricted-exports": "off",
      "no-restricted-imports": "off",
      "no-restricted-properties": "off",
      "no-restricted-syntax": "off",
      "no-return-await": "off",
      "no-script-url": "off",
      "no-self-compare": "off",
      "no-shadow": "off",
      "no-sync": "off",
      "no-ternary": "off",
      "no-this-before-super": "off",
      "no-throw-literal": "off",
      "no-trailing-spaces": "off",
      "no-undef-init": "off",
      "no-undefined": "off",
      "no-underscore-dangle": "off",
      "no-unexpected-multiline": "off",
      "no-unneeded-ternary": "off",
      "no-unreachable-loop": "off",
      "no-unsafe-finally": "off",
      "no-unsafe-negation": "off",
      "no-unsafe-optional-chaining": "off",
      "no-unused-private-class-members": "off",
      "no-unused-vars": "off",
      "no-use-before-define": "off",
      "no-useless-backreference": "off",
      "no-useless-call": "off",
      "no-useless-catch": "off",
      "no-useless-computed-key": "off",
      "no-useless-concat": "off",
      "no-useless-constructor": "off",
      "no-useless-escape": "off",
      "no-useless-rename": "off",
      "no-useless-return": "off",
      "no-var": "off",
      "no-void": "off",
      "no-warning-comments": "off",
      "no-whitespace-before-property": "off",
      "no-with": "off",
      "object-shorthand": "off",
      "one-var": "off",
      "operator-assignment": "off",
      "prefer-arrow-callback": "off",
      "prefer-const": "off",
      "prefer-destructuring": "off",
      "prefer-exponentiation-operator": "off",
      "prefer-named-capture-group": "off",
      "prefer-numeric-literals": "off",
      "prefer-object-has-own": "off",
      "prefer-object-spread": "off",
      "prefer-promise-reject-errors": "off",
      "prefer-regex-literals": "off",
      "prefer-rest-params": "off",
      "prefer-spread": "off",
      "prefer-template": "off",
      "quote-props": "off",
      "radix": "off",
      "require-atomic-updates": "off",
      "require-await": "off",
      "require-unicode-regexp": "off",
      "require-yield": "off",
      "rest-spread-spacing": "off",
      "semi": "off",
      "semi-spacing": "off",
      "semi-style": "off",
      "sort-imports": "off",
      "sort-keys": "off",
      "sort-vars": "off",
      "space-before-blocks": "off",
      "space-before-function-paren": "off",
      "space-in-parens": "off",
      "space-infix-ops": "off",
      "space-unary-ops": "off",
      "spaced-comment": "off",
      "strict": "off",
      "switch-colon-spacing": "off",
      "symbol-description": "off",
      "template-curly-spacing": "off",
      "template-tag-spacing": "off",
      "unicode-bom": "off",
      "vars-on-top": "off",
      "wrap-iife": "off",
      "wrap-regex": "off",
      "yoda": "off",

      // React-specific
      "react/display-name": "off",
      "react/jsx-key": "off",
      "react/jsx-no-comment-textnodes": "off",
      "react/jsx-no-duplicate-props": "off",
      "react/jsx-no-target-blank": "off",
      "react/jsx-no-undef": "off",
      "react/jsx-uses-react": "off",
      "react/jsx-uses-vars": "off",
      "react/no-children-prop": "off",
      "react/no-danger-with-children": "off",
      "react/no-deprecated": "off",
      "react/no-direct-mutation-state": "off",
      "react/no-find-dom-node": "off",
      "react/no-is-mounted": "off",
      "react/no-render-return-value": "off",
      "react/no-string-refs": "off",
      "react/no-unescaped-entities": "off",
      "react/no-unknown-property": "off",
      "react/no-unsafe": "off",
      "react/no-unstable-nested-components": "off",
      "react/no-unused-prop-types": "off",
      "react/no-unused-state": "off",
      "react/prefer-es6-class": "off",
      "react/react-in-jsx-scope": "off",
      "react/require-render-return": "off",
      "react/self-closing-comp": "off",
      "react/sort-comp": "off",
      "react/style-prop-object": "off",
      "react/void-dom-elements-no-children": "off",

      // React Hooks
      "react-hooks/rules-of-hooks": "error",
      "react-hooks/exhaustive-deps": "warn",
    },
  },

  // Node.js scripts (no browser globals)
  {
    files: ["scripts/**/*.{js,mjs}", "integraciones/**/*.py", "web/invitation/tests/**/*.mjs"],
    languageOptions: {
      globals: {
        ...globals.node,
      },
    },
  },
];
