/**
 * Guest registry — re-export from the shared module.
 * The actual data is GENERATED by scripts/generate-guests.mjs into
 * web/shared/guests.js from the live Google Sheet Invitados tab (source of truth).
 * This file exists so existing imports (`./guests.js`) keep working.
 */
export {
  AUTH_EMAIL_DOMAIN,
  SHARED_PASSWORD,
  getGuestByUsername,
  getGuestByEmail,
  getGuest,
  getActiveGuests,
  getGuestsByUnit,
} from "../../shared/guests.js";
export { default } from "../../shared/guests.js";
