export const coast = {
  es: {
    eyebrow: "Del 12 al 28 de febrero",
    title: "Dos semanas de fiesta",
    body:
      "Este es el hilo de nuestras dos semanas juntos — antes, durante y después de la boda. Vota directamente en las paradas que te tienten.",
    nightsLabel: { one: "noche", other: "noches" },
    plans: [
      {
        icon: "🌊",
        dates: "Vie 12 → Mar 16",
        title: "Playa · Bahía de Banderas",
        body: "Tres destinos para elegir.",
        kind: "plan",
        questionId: "playa",
        nights: 4,
        subDestinations: [
          { name: "Puerto Vallarta", tag: "Vibrante", gallery: "vallarta", questionId: "vallarta" },
          { name: "San Pancho", tag: "Surf", gallery: "sanPancho", questionId: "sanPancho" },
          { name: "Chacala", tag: "Calma", gallery: "chacala", questionId: "chacala" },
        ],
      },
      {
        icon: "🏙️",
        dates: "Mar 16 → Jue 18",
        title: "Guadalajara",
        body: "Ciudad, traslados y descanso.",
        kind: "marker",
        nights: 2,
        gallery: "guadalajara",
      },
      {
        icon: "🌙",
        dates: "Jue 18 → Vie 19",
        title: "Roca Azul · 1 noche antes",
        body: "Llegada temprana al lugar.",
        kind: "marker",
        nights: 1,
        gallery: "rocaAzul",
      },
      {
        icon: "💍",
        dates: "Vie 19 → Dom 21",
        title: "La boda",
        body: "Roca Azul · Jocotepec.",
        kind: "wedding",
        nights: 2,
        gallery: "rocaAzul",
      },
      {
        icon: "🏡",
        dates: "Dom 21 → Mar 23",
        title: "Roca Azul · 2 días más",
        body: "Seguir en el lugar.",
        kind: "plan",
        questionId: "rocaAzul",
        nights: 2,
        gallery: "rocaAzul",
      },
      {
        icon: "⛰️",
        dates: "Mar 23 → Jue 25",
        title: "Tapalpa",
        body: "Pueblo mágico en la sierra.",
        kind: "plan",
        questionId: "tapalpa",
        nights: 2,
        gallery: "tapalpa",
      },
      {
        icon: "🏖️",
        dates: "Jue 25 → Dom 28",
        title: "Barra de Navidad",
        body: "Playa en la Costa Alegre.",
        kind: "plan",
        questionId: "barraNavidad",
        nights: 3,
        gallery: "barra",
      },
    ],
    note:
      "Las fechas exactas y el transporte dependerán del número de personas interesadas.",
    vote: {
      label: "Tu voto",
      noAnswer: "Sin responder",
      button: "Votar",
    },
    rsvpMini: {
      eyebrow: "Del 12 al 28 de febrero",
      title: "Tus votos",
      intro:
        "Vota qué tan probable es que te unas a cada parada. Puedes cambiar tu respuesta en cualquier momento.",
      questions: [
        {
          id: "playa",
          title: "Bahía de Banderas",
          subtitle: "¿Vendrás al plan de playa?",
        },
        {
          id: "vallarta",
          title: "Puerto Vallarta",
          subtitle: "Del viernes 12 al martes 16 · Vibrante.",
        },
        {
          id: "sanPancho",
          title: "San Pancho",
          subtitle: "Del viernes 12 al martes 16 · Surf.",
        },
        {
          id: "chacala",
          title: "Chacala",
          subtitle: "Del viernes 12 al martes 16 · Calma.",
        },
        {
          id: "rocaAzul",
          title: "Roca Azul (2 días más)",
          subtitle: "Del domingo 21 al martes 23.",
        },
        {
          id: "tapalpa",
          title: "Tapalpa",
          subtitle: "Del martes 23 al jueves 25.",
        },
        {
          id: "barraNavidad",
          title: "Barra de Navidad",
          subtitle: "Del jueves 25 al domingo 28.",
        },
      ],
      recapTitle: "Resumen",
      recapProgress: "respondidos",
      modifyButton: "Modificar mis respuestas",
      button: "Guardar mis respuestas",
      success: "¡Gracias! Guardamos tus respuestas.",
      error: "No pudimos guardar. Revisa tu conexión e inténtalo de nuevo.",
    },
  },
  fr: {
    eyebrow: "Du 12 au 28 février",
    title: "Deux semaines de fête",
    body:
      "Voici le fil de nos deux semaines ensemble — avant, pendant et après le mariage. Vote directement sur les étapes qui te tentent.",
    nightsLabel: { one: "nuit", other: "nuits" },
    plans: [
      {
        icon: "🌊",
        dates: "Ven 12 → Mar 16",
        title: "Plage · Bahía de Banderas",
        body: "Trois destinations au choix.",
        kind: "plan",
        questionId: "playa",
        nights: 4,
        subDestinations: [
          { name: "Puerto Vallarta", tag: "Vibrant", gallery: "vallarta", questionId: "vallarta" },
          { name: "San Pancho", tag: "Surf", gallery: "sanPancho", questionId: "sanPancho" },
          { name: "Chacala", tag: "Calme", gallery: "chacala", questionId: "chacala" },
        ],
      },
      {
        icon: "🏙️",
        dates: "Mar 16 → Jeu 18",
        title: "Guadalajara",
        body: "Ville, transferts et repos.",
        kind: "marker",
        nights: 2,
        gallery: "guadalajara",
      },
      {
        icon: "🌙",
        dates: "Jeu 18 → Ven 19",
        title: "Roca Azul · 1 nuit avant",
        body: "Arrivée tôt sur place.",
        kind: "marker",
        nights: 1,
        gallery: "rocaAzul",
      },
      {
        icon: "💍",
        dates: "Ven 19 → Dim 21",
        title: "Le mariage",
        body: "Roca Azul · Jocotepec.",
        kind: "wedding",
        nights: 2,
        gallery: "rocaAzul",
      },
      {
        icon: "🏡",
        dates: "Dim 21 → Mar 23",
        title: "Roca Azul · 2 jours de plus",
        body: "Rester sur place.",
        kind: "plan",
        questionId: "rocaAzul",
        nights: 2,
        gallery: "rocaAzul",
      },
      {
        icon: "⛰️",
        dates: "Mar 23 → Jeu 25",
        title: "Tapalpa",
        body: "Pueblo mágico dans la sierra.",
        kind: "plan",
        questionId: "tapalpa",
        nights: 2,
        gallery: "tapalpa",
      },
      {
        icon: "🏖️",
        dates: "Jeu 25 → Dim 28",
        title: "Barra de Navidad",
        body: "Plage sur la Costa Alegre.",
        kind: "plan",
        questionId: "barraNavidad",
        nights: 3,
        gallery: "barra",
      },
    ],
    note:
      "Les dates exactes et le transport dépendront du nombre de personnes intéressées.",
    vote: {
      label: "Ton vote",
      noAnswer: "Sans réponse",
      button: "Voter",
    },
    rsvpMini: {
      eyebrow: "Du 12 au 28 février",
      title: "Tes votes",
      intro:
        "Vote pour dire à quel point tu as envie de rejoindre chaque étape. Tu peux modifier ta réponse à tout moment.",
      questions: [
        {
          id: "playa",
          title: "Bahía de Banderas",
          subtitle: "Viens-tu au plan plage ?",
        },
        {
          id: "vallarta",
          title: "Puerto Vallarta",
          subtitle: "Du vendredi 12 au mardi 16 · Vibrant.",
        },
        {
          id: "sanPancho",
          title: "San Pancho",
          subtitle: "Du vendredi 12 au mardi 16 · Surf.",
        },
        {
          id: "chacala",
          title: "Chacala",
          subtitle: "Du vendredi 12 au mardi 16 · Calme.",
        },
        {
          id: "rocaAzul",
          title: "Roca Azul (2 jours de plus)",
          subtitle: "Du dimanche 21 au mardi 23.",
        },
        {
          id: "tapalpa",
          title: "Tapalpa",
          subtitle: "Du mardi 23 au jeudi 25.",
        },
        {
          id: "barraNavidad",
          title: "Barra de Navidad",
          subtitle: "Du jeudi 25 au dimanche 28.",
        },
      ],
      recapTitle: "Résumé",
      recapProgress: "répondu·e·s",
      modifyButton: "Modifier mes réponses",
      button: "Enregistrer mes réponses",
      success: "Merci ! Nous avons enregistré tes réponses.",
      error: "Impossible d’enregistrer. Vérifie ta connexion et réessaie.",
    },
  },
  en: {
    eyebrow: "February 12–28",
    title: "Two weeks of celebration",
    body:
      "Here is the thread of our two weeks together — before, during and after the wedding. Vote directly on the stops that tempt you.",
    nightsLabel: { one: "night", other: "nights" },
    plans: [
      {
        icon: "🌊",
        dates: "Fri 12 → Tue 16",
        title: "Beach · Bahía de Banderas",
        body: "Three destinations to choose from.",
        kind: "plan",
        questionId: "playa",
        nights: 4,
        subDestinations: [
          { name: "Puerto Vallarta", tag: "Vibrant", gallery: "vallarta", questionId: "vallarta" },
          { name: "San Pancho", tag: "Surf", gallery: "sanPancho", questionId: "sanPancho" },
          { name: "Chacala", tag: "Calm", gallery: "chacala", questionId: "chacala" },
        ],
      },
      {
        icon: "🏙️",
        dates: "Tue 16 → Thu 18",
        title: "Guadalajara",
        body: "City, transfers and rest.",
        kind: "marker",
        nights: 2,
        gallery: "guadalajara",
      },
      {
        icon: "🌙",
        dates: "Thu 18 → Fri 19",
        title: "Roca Azul · 1 night before",
        body: "Early arrival at the venue.",
        kind: "marker",
        nights: 1,
        gallery: "rocaAzul",
      },
      {
        icon: "💍",
        dates: "Fri 19 → Sun 21",
        title: "The wedding",
        body: "Roca Azul · Jocotepec.",
        kind: "wedding",
        nights: 2,
        gallery: "rocaAzul",
      },
      {
        icon: "🏡",
        dates: "Sun 21 → Tue 23",
        title: "Roca Azul · 2 more days",
        body: "Stay on at the venue.",
        kind: "plan",
        questionId: "rocaAzul",
        nights: 2,
        gallery: "rocaAzul",
      },
      {
        icon: "⛰️",
        dates: "Tue 23 → Thu 25",
        title: "Tapalpa",
        body: "Magical mountain town.",
        kind: "plan",
        questionId: "tapalpa",
        nights: 2,
        gallery: "tapalpa",
      },
      {
        icon: "🏖️",
        dates: "Thu 25 → Sun 28",
        title: "Barra de Navidad",
        body: "Beach on the Costalegre.",
        kind: "plan",
        questionId: "barraNavidad",
        nights: 3,
        gallery: "barra",
      },
    ],
    note:
      "The exact dates and transport will depend on the number of interested guests.",
    vote: {
      label: "Your vote",
      noAnswer: "No answer",
      button: "Vote",
    },
    rsvpMini: {
      eyebrow: "February 12–28",
      title: "Your votes",
      intro:
        "Vote on how likely you are to join each stop. You can change your answer at any time.",
      questions: [
        {
          id: "playa",
          title: "Bahía de Banderas",
          subtitle: "Will you come to the beach plan?",
        },
        {
          id: "vallarta",
          title: "Puerto Vallarta",
          subtitle: "From Friday 12 to Tuesday 16 · Vibrant.",
        },
        {
          id: "sanPancho",
          title: "San Pancho",
          subtitle: "From Friday 12 to Tuesday 16 · Surf.",
        },
        {
          id: "chacala",
          title: "Chacala",
          subtitle: "From Friday 12 to Tuesday 16 · Calm.",
        },
        {
          id: "rocaAzul",
          title: "Roca Azul (2 more days)",
          subtitle: "From Sunday 21 to Tuesday 23.",
        },
        {
          id: "tapalpa",
          title: "Tapalpa",
          subtitle: "From Tuesday 23 to Thursday 25.",
        },
        {
          id: "barraNavidad",
          title: "Barra de Navidad",
          subtitle: "From Thursday 25 to Sunday 28.",
        },
      ],
      recapTitle: "Summary",
      recapProgress: "answered",
      modifyButton: "Modify my answers",
      button: "Save my answers",
      success: "Thank you! We saved your answers.",
      error: "We could not save. Check your connection and try again.",
    },
  },
};
