export const songRequest = {
  es: {
    eyebrow: "Pide tu canción",
    title: "¿Qué canción no puede faltar?",
    body:
      "Dinos qué canción quieres escuchar, cantar o bailar. Si quieres subir al escenario, elige la opción de karaoke o de banda en vivo y quizá podamos acompañarte.",
    songLabel: "Canción (título y artista)",
    songPlaceholder: "Ej. La Bikina · Luis Miguel",
    searchHint: "Escribe al menos 2 letras para buscar.",
    searching: "Buscando…",
    noResults: "No encontramos canciones. Escribe el título y artista.",
    searchError: "No pudimos buscar. Inténtalo de nuevo.",
    selectSong: "Selecciona una canción",
    intentLabel: "¿Qué quieres hacer con ella?",
    intents: {
      hear: "Quiero escucharla",
      sing: "Quiero cantarla en el escenario con los músicos",
      karaoke: "Quiero cantarla en el karaoke",
      band: "Quiero que la toquen los músicos en vivo",
    },
    bandTypeLabel: "¿Qué banda quieres que la toque?",
    bandTypes: {
      marimba: "Marimba",
      mariachi: "Mariachi",
      norteno: "Norteño",
      frenchBand: "Fanfare francesa",
    },
    
    submit: "Enviar mi canción",
    success: "¡Gracias! Tu canción está en la lista.",
    error: "No pudimos guardar tu canción. Inténtalo de nuevo.",
    required: "Escribe el título de la canción.",
  },
  fr: {
    eyebrow: "Demande ta chanson",
    title: "Quelle chanson ne peut pas manquer ?",
    body:
      "Dis-nous quelle chanson tu veux écouter, chanter ou danser. Si tu veux monter sur scène, choisis l’option karaoké ou fanfare live et nous pourrons peut-être t’accompagner.",
    songLabel: "Chanson (titre et artiste)",
    songPlaceholder: "Ex. La Bikina · Luis Miguel",
    searchHint: "Écris au moins 2 lettres pour rechercher.",
    searching: "Recherche…",
    noResults: "Aucune chanson trouvée. Écris le titre et l’artiste.",
    searchError: "Impossible de rechercher. Réessaie.",
    selectSong: "Sélectionne une chanson",
    intentLabel: "Qu’aimerais-tu en faire ?",
    intents: {
      hear: "Je veux l’écouter",
      sing: "Je veux la chanter sur scène avec les musiciens",
      karaoke: "Je veux la chanter au karaoké",
      band: "Je veux que les musiciens la jouent en live",
    },
    bandTypeLabel: "Quelle fanfare veux-tu qu’elle la joue ?",
    bandTypes: {
      marimba: "Marimba",
      mariachi: "Mariachi",
      norteno: "Norteño",
      frenchBand: "Fanfare française",
    },
    submit: "Envoyer ma chanson",
    
    success: "Merci ! Ta chanson est sur la liste.",
    error: "Impossible d’enregistrer ta chanson. Réessaie.",
    required: "Écris le titre de la chanson.",
  },
  en: {
    eyebrow: "Request your song",
    title: "Which song can’t be missing?",
    body:
      "Tell us which song you want to hear, sing, or dance to. If you want to take the stage, choose the karaoke or live band option and we may be able to accompany you.",
    songLabel: "Song (title and artist)",
    songPlaceholder: "E.g. La Bikina · Luis Miguel",
    searchHint: "Type at least 2 letters to search.",
    searching: "Searching…",
    noResults: "No songs found. Enter the title and artist.",
    searchError: "We could not search. Please try again.",
    selectSong: "Select a song",
    intentLabel: "What would you like to do with it?",
    intents: {
      hear: "I want to hear it",
      sing: "I want to sing it on stage with the musicians",
      karaoke: "I want to sing it at karaoke",
      band: "I want the musicians to play it live",
    },
    bandTypeLabel: "Which band would you like to play it?",
    bandTypes: {
      marimba: "Marimba",
      mariachi: "Mariachi",
      norteno: "Norteño",
      frenchBand: "French band",
    },
    submit: "Send my song",
    
    success: "Thank you! Your song is on the list.",
    error: "We could not save your song. Please try again.",
    required: "Enter the song title.",
  },
};
