export const songRequest = {
  es: {
    eyebrow: "Pide tu canción",
    title: "¡Baila, canta o sube al escenario con los músicos!",
    body:
      "Dinos qué canción quieres escuchar, cantar o bailar. Si quieres subir al escenario, elige la opción de karaoke o de banda en vivo y quizá podamos acompañarte.",
    songLabel: "Canción (título y artista)",
    songPlaceholder: "Ej. La Bikina · Luis Miguel",
    searchHint: "Escribe al menos 2 letras para buscar.",
    searching: "Buscando…",
    noResults: "No encontramos canciones. Escribe el título y artista.",
    searchError: "No pudimos buscar. Inténtalo de nuevo.",
    selectSong: "Selecciona una canción",
    intentLabel: "¿Qué quieres hacer con ella?",
    intents: {
      hear: "Quiero escucharla",
      sing: "Quiero cantarla en el escenario con los músicos",
      karaoke: "Quiero cantarla en el karaoke",
      band: "Quiero que la toquen los músicos en vivo",
    },
    bandTypeLabel: "¿Qué banda quieres que la toque?",
    bandTypes: {
      marimba: "Marimba",
      mariachi: "Mariachi",
      norteno: "Norteño",
      frenchBand: "Fanfare francesa",
    },
    assignedGuestLabel: "¿Para quién es la canción?",
    assignedGuestMe: "Para mí",
    assignedGuestFor: "Para {name}",
    
    submit: "Enviar mi canción",

    success: "¡Gracias! Tu canción está en la lista.",
    error: "No pudimos guardar tu canción. Inténtalo de nuevo.",
    required: "Escribe el título de la canción.",
    mySongsTitle: "Mis canciones",
    mySongsEmpty: "Aún no has pedido ninguna canción.",
    mySongsLoading: "Cargando tus canciones…",
    mySongsError: "No pudimos cargar tus canciones. Inténtalo de nuevo.",
    edit: "Editar",
    delete: "Eliminar",
    deleteConfirm: "¿Eliminar esta canción de la lista?",
    deleteSuccess: "Canción eliminada.",
    deleteError: "No pudimos eliminar la canción. Inténtalo de nuevo.",
    updateSuccess: "¡Canción actualizada!",
    updateError: "No pudimos actualizar la canción. Inténtalo de nuevo.",
    cancelEdit: "Cancelar edición",
    editing: "Editando tu canción",
    saveEdit: "Guardar cambios",
  },


  fr: {
    eyebrow: "Demande ta chanson",
    title: "Danse, chante ou monte sur scène avec les musiciens !",
    body:
      "Dis-nous quelle chanson tu veux écouter, chanter ou danser. Si tu veux monter sur scène, choisis l’option karaoké ou fanfare live et nous pourrons peut-être t’accompagner.",
    songLabel: "Chanson (titre et artiste)",
    songPlaceholder: "Ex. La Bikina · Luis Miguel",
    searchHint: "Écris au moins 2 lettres pour rechercher.",
    searching: "Recherche…",
    noResults: "Aucune chanson trouvée. Écris le titre et l’artiste.",
    searchError: "Impossible de rechercher. Réessaie.",
    selectSong: "Sélectionne une chanson",
    intentLabel: "Qu’aimerais-tu en faire ?",
    intents: {
      hear: "Je veux l’écouter",
      sing: "Je veux la chanter sur scène avec les musiciens",
      karaoke: "Je veux la chanter au karaoké",
      band: "Je veux que les musiciens la jouent en live",
    },
    bandTypeLabel: "Quelle fanfare veux-tu qu’elle la joue ?",
    bandTypes: {
      marimba: "Marimba",
      mariachi: "Mariachi",
      norteno: "Norteño",
      frenchBand: "Fanfare française",
    },
    assignedGuestLabel: "Pour qui est la chanson ?",
    assignedGuestMe: "Pour moi",
    assignedGuestFor: "Pour {name}",
    submit: "Envoyer ma chanson",

    
    success: "Merci ! Ta chanson est sur la liste.",
    error: "Impossible d’enregistrer ta chanson. Réessaie.",
    required: "Écris le titre de la chanson.",
    mySongsTitle: "Mes chansons",
    mySongsEmpty: "Tu n’as encore demandé aucune chanson.",
    mySongsLoading: "Chargement de tes chansons…",
    mySongsError: "Impossible de charger tes chansons. Réessaie.",
    edit: "Modifier",
    delete: "Supprimer",
    deleteConfirm: "Supprimer cette chanson de la liste ?",
    deleteSuccess: "Chanson supprimée.",
    deleteError: "Impossible de supprimer la chanson. Réessaie.",
    updateSuccess: "Chanson mise à jour !",
    updateError: "Impossible de mettre à jour la chanson. Réessaie.",
    cancelEdit: "Annuler la modification",
    editing: "Modification de ta chanson",
    saveEdit: "Enregistrer les modifications",
  },


  en: {
    eyebrow: "Request your song",
    title: "Dance, sing, or take the stage with the musicians!",
    body:
      "Tell us which song you want to hear, sing, or dance to. If you want to take the stage, choose the karaoke or live band option and we may be able to accompany you.",
    songLabel: "Song (title and artist)",
    songPlaceholder: "E.g. La Bikina · Luis Miguel",
    searchHint: "Type at least 2 letters to search.",
    searching: "Searching…",
    noResults: "No songs found. Enter the title and artist.",
    searchError: "We could not search. Please try again.",
    selectSong: "Select a song",
    intentLabel: "What would you like to do with it?",
    intents: {
      hear: "I want to hear it",
      sing: "I want to sing it on stage with the musicians",
      karaoke: "I want to sing it at karaoke",
      band: "I want the musicians to play it live",
    },
    bandTypeLabel: "Which band would you like to play it?",
    bandTypes: {
      marimba: "Marimba",
      mariachi: "Mariachi",
      norteno: "Norteño",
      frenchBand: "French band",
    },
    assignedGuestLabel: "Who is the song for?",
    assignedGuestMe: "For me",
    assignedGuestFor: "For {name}",
    submit: "Send my song",

    
    success: "Thank you! Your song is on the list.",
    error: "We could not save your song. Please try again.",
    required: "Enter the song title.",
    mySongsTitle: "My songs",
    mySongsEmpty: "You haven’t requested any songs yet.",
    mySongsLoading: "Loading your songs…",
    mySongsError: "We could not load your songs. Please try again.",
    edit: "Edit",
    delete: "Delete",
    deleteConfirm: "Delete this song from the list?",
    deleteSuccess: "Song deleted.",
    deleteError: "We could not delete the song. Please try again.",
    updateSuccess: "Song updated!",
    updateError: "We could not update the song. Please try again.",
    cancelEdit: "Cancel editing",
    editing: "Editing your song",
    saveEdit: "Save changes",
  },
};
