export const suggestions = {
  es: {
    
          fields: {
            name: "Tu nombre",
            dessert: "¿Qué postre prefieres?",
            food: "¿Qué falta o qué te gustaría agregar?",
            song: "Canción sugerida",
            artist: "Artista o versión",
            sing: "¿Quieres cantarla?",
            extra: "Otra idea para la fiesta",
            genres: "¿Qué géneros no pueden faltar?",
          },
          genres: [
            "Cumbia",
            "Salsa",
            "Bachata",
            "Reggaetón",
            "Norteño",
            "Banda",
            "Mariachi",
            "Ranchera",
            "Pop",
            "Rock",
            "Electrónica",
            "Hip-hop",
            "Jazz",
            "Soul / Funk",
            "Disco",
            "Música francesa",
            "Música de los 80",
            "Música de los 90",
            "Baladas",
            "Karaoke",
          ],
    
          options: {
            dessert: [
              { value: "jericalla", label: "Jericalla" },
              { value: "gelatinas", label: "Gelatinas" },
              { value: "both", label: "¡Las dos!" },
              { value: "other", label: "Tengo otra sugerencia" },
            ],
            sing: [
              { value: "yes", label: "Sí, me gustaría cantarla" },
              { value: "maybe", label: "Tal vez, anímenme" },
              { value: "request", label: "Solo quiero escucharla" },
            ],
          },
          button: "Enviar mis sugerencias",
          previewNote:
            "Tus canciones, votos e ideas se guardarán de forma privada.",
  },
  fr: {
    fields: {
      name: "Ton nom",
    
      dessert: "Quel dessert préfères-tu ?",
      food: "Que manque-t-il ou qu’aimerais-tu ajouter ?",
      song: "Chanson proposée",
      artist: "Artiste ou version",
      sing: "Souhaites-tu la chanter ?",
      extra: "Une autre idée pour la fête",
      genres: "Quels genres ne peuvent pas manquer ?",
    },
    genres: [
      "Cumbia",
      "Salsa",
      "Bachata",
      "Reggaeton",
      "Norteño",
      "Banda",
      "Mariachi",
      "Ranchera",
      "Pop",
      "Rock",
      "Électro",
      "Hip-hop",
      "Jazz",
      "Soul / Funk",
      "Disco",
      "Musique française",
      "Années 80",
      "Années 90",
      "Ballades",
      "Karaoké",
    ],
    
    options: {
      dessert: [
        { value: "jericalla", label: "Jericalla" },
        { value: "gelatinas", label: "Gelées mexicaines" },
        { value: "both", label: "Les deux !" },
        { value: "other", label: "J’ai une autre suggestion" },
      ],
      sing: [
        { value: "yes", label: "Oui, j’aimerais la chanter" },
        { value: "maybe", label: "Peut-être, encourage-moi" },
        { value: "request", label: "Je veux simplement l’entendre" },
      ],
    },
    button: "Envoyer mes suggestions",
    previewNote:
      "Tes chansons, votes et idées seront enregistrés de façon privée.",
  },
  en: {
    fields: {
      name: "Your name",
    
      dessert: "Which dessert would you prefer?",
      food: "What is missing or what would you add?",
      song: "Song suggestion",
      artist: "Artist or version",
      sing: "Would you like to sing it?",
      extra: "Another idea for the celebration",
      genres: "Which genres are a must?",
    },
    genres: [
      "Cumbia",
      "Salsa",
      "Bachata",
      "Reggaeton",
      "Norteño",
      "Banda",
      "Mariachi",
      "Ranchera",
      "Pop",
      "Rock",
      "Electronic",
      "Hip-hop",
      "Jazz",
      "Soul / Funk",
      "Disco",
      "French music",
      "80s music",
      "90s music",
      "Ballads",
      "Karaoke",
    ],
    
    options: {
      dessert: [
        { value: "jericalla", label: "Jericalla" },
        { value: "gelatinas", label: "Mexican jellies" },
        { value: "both", label: "Both!" },
        { value: "other", label: "I have another suggestion" },
      ],
      sing: [
        { value: "yes", label: "Yes, I would like to sing it" },
        { value: "maybe", label: "Maybe—encourage me" },
        { value: "request", label: "I only want to hear it" },
      ],
    },
    button: "Send my suggestions",
    previewNote:
      "Your songs, votes, and ideas will be saved privately.",
  },
};
