export const travel = {
  es: {
    
    
          eyebrow: "Vengo de lejos",
          title: "Tu viaje también forma parte de la celebración",
          body:
            "Acompañaremos personalmente a quienes lo deseen y vengan desde Europa y otros lugares: elección de vuelos, llegada a Guadalajara, alojamiento y traslados.",
          points: [
            "Madrid–Guadalajara, operado por Aeromexico, es la conexión directa prioritaria desde Europa.",
            "Estaremos encantados de ayudarte a organizar tu estancia y tus traslados.",
            "No dudes en contactarnos directamente si necesitas consejos para organizar tu viaje y tu estancia en México. ¡Nos encanta compartir nuestros consejos de este país de mil facetas!",
          ],
          routes: {
            eyebrow: "Mapa de trayectos",
    
            title: "Llegar a Roca Azul y seguir hacia la costa",
            note:
              "Las duraciones indicadas son orientativas y pueden variar enormemente. Sé previsor y, mejor aún, está en el lugar con anticipación reservando un alojamiento si puedes.",
            venue: "Roca Azul · Jocotepec",
            toVenueLabel: "Hacia Roca Azul",
            toBeachLabel: "Hacia la playa",
            originsLabel: "Hacia la boda",
            destinationsLabel: "Después de la boda",
            mapLabel: "Mapa de Roca Azul y sus alrededores",
            directionsLabel: "Cómo llegar (rutas en Google Maps)",
            origins: [
              { place: "Centro de Guadalajara", duration: "≈ 1 h 30", detail: "Ruta libre" },
    
              { place: "Nuestra casa · Tesistán", duration: "≈ 1 h 45", detail: "Ruta libre" },
              { place: "Aeropuerto GDL", duration: "≈ 1 h", detail: "Ruta libre" },
            ],
            destinations: [
              {
                place: "Barra de Navidad",
                duration: "≈ 5 h",
                detail: "Libre · Cocula → Autlán → Barra",
              },
              {
                place: "Barra de Navidad",
                duration: "≈ 4 h 45",
                detail: "Vía Manzanillo · casetas ≈ $500 MXN",
              },
            {
              place: "Manzanillo",
              duration: "≈ 4 h 30",
              detail: "Casetas ≈ $500 MXN",
            },
          ],
          maps: {
            venueLabel: "Cómo llegar al lugar",
            beachLabel: "Cómo llegar a la playa",
          },
        },
          cta: "Compartir mis datos de viaje",
    
          ctaNote: "El formulario privado ya está disponible más abajo.",
          vuelosImage: "vuelos_c6qdcq",
          vuelosLabel: "Mapa de vuelos",
          flightInfo: {
            eyebrow: "Mis datos de vuelo",
            title: "Cuéntanos cómo llegas",
            body:
              "Comparte tus datos de vuelo para que podamos organizar tu llegada a Guadalajara y tus traslados. Puedes guardar y modificar esta información cuando quieras.",
            originLabel: "Salida (origen)",
            originPlaceholder: "Busca tu aeropuerto de salida…",
            destinationLabel: "Llegada (destino)",
            destinationPlaceholder: "Busca tu aeropuerto de llegada…",
            connectionsLabel: "Escalas",
            connectionsHint: "Añade hasta 3 aeropuertos de escala (opcional).",
            addConnection: "Añadir escala",
            removeConnection: "Quitar escala",
            arrivalDateLabel: "Fecha de llegada",
            arrivalTimeLabel: "Hora de llegada",
            finalFlightLabel: "Número de vuelo final",
            finalFlightPlaceholder: "Ej. AM 58",
            save: "Guardar mis datos de vuelo",
            saving: "Guardando…",
            saved: "¡Datos de vuelo guardados!",
            error: "No se pudieron guardar tus datos. Inténtalo de nuevo.",
            empty: "Aún no has compartido tus datos de vuelo.",
            searchHint: "Escribe el nombre de la ciudad o el código del aeropuerto.",
            noResults: "No encontramos aeropuertos. Revisa el nombre o el código.",
            departure: {
              eyebrow: "Mis datos de regreso",
              title: "Cuéntanos cómo te regresas",
              body:
                "Comparte tus datos de vuelo de regreso para que podamos organizar tu salida de Guadalajara y tus traslados. Puedes guardar y modificar esta información cuando quieras.",
              originLabel: "Salida (origen)",
              originPlaceholder: "Busca tu aeropuerto de salida…",
              destinationLabel: "Llegada (destino)",
              destinationPlaceholder: "Busca tu aeropuerto de llegada…",
              connectionsLabel: "Escalas",
              connectionsHint: "Añade hasta 3 aeropuertos de escala (opcional).",
              addConnection: "Añadir escala",
              removeConnection: "Quitar escala",
              departureDateLabel: "Fecha de salida",
              departureTimeLabel: "Hora de salida",
              finalFlightLabel: "Número de vuelo final",
              finalFlightPlaceholder: "Ej. AM 58",
              save: "Guardar mis datos de regreso",
              saving: "Guardando…",
              saved: "¡Datos de regreso guardados!",
              error: "No se pudieron guardar tus datos. Inténtalo de nuevo.",
              empty: "Aún no has compartido tus datos de regreso.",
              searchHint: "Escribe el nombre de la ciudad o el código del aeropuerto.",
              noResults: "No encontramos aeropuertos. Revisa el nombre o el código.",
            },
          },
  },
  fr: {
    
    
          eyebrow: "Je viens de loin",
          title: "Ton voyage fait aussi partie de la fête",
          body:
            "Nous accompagnerons personnellement celles et ceux qui le souhaitent et qui viennent d’Europe et d’ailleurs : choix des vols, arrivée à Guadalajara, hébergement et transferts.",
          points: [
            "Madrid–Guadalajara, opéré par Aeromexico, est la liaison directe prioritaire depuis l’Europe.",
            "Nous serons ravis de t’aider à organiser ton séjour et tes transferts.",
            "N’hésite pas à nous contacter directement si tu as besoin de conseils pour organiser ton voyage et ton séjour au Mexique ! Nous adorons partager nos conseils de ce pays aux mille facettes !",
          ],
          routes: {
            eyebrow: "Schéma des trajets",
    
            title: "Rejoindre Roca Azul, puis continuer vers la côte",
            note:
              "Les durées indiquées sont indicatives et peuvent varier énormément. Sois prévoyant et, encore mieux, sois sur place en avance en réservant un logement si tu peux.",
            venue: "Roca Azul · Jocotepec",
            toVenueLabel: "Vers Roca Azul",
            toBeachLabel: "Vers la plage",
            originsLabel: "Vers le mariage",
            destinationsLabel: "Après le mariage",
            mapLabel: "Carte de Roca Azul et de ses environs",
            directionsLabel: "Itinéraires (routes sur Google Maps)",
            origins: [
              { place: "Centre de Guadalajara", duration: "≈ 1 h 30", detail: "Route gratuite" },
    
              { place: "Notre maison · Tesistán", duration: "≈ 1 h 45", detail: "Route gratuite" },
              { place: "Aéroport GDL", duration: "≈ 1 h", detail: "Route gratuite" },
            ],
            destinations: [
              {
                place: "Barra de Navidad",
                duration: "≈ 5 h",
                detail: "Sans péage · Cocula → Autlán → Barra",
              },
              {
                place: "Barra de Navidad",
                duration: "≈ 4 h 45",
                detail: "Via Manzanillo · péages ≈ 500 MXN",
              },
              {
                place: "Manzanillo",
                duration: "≈ 4 h 30",
                detail: "Péages ≈ 500 MXN",
              },
            ],
            maps: {
              venueLabel: "Comment rejoindre le lieu",
              beachLabel: "Comment rejoindre la plage",
            },
          },
          cta: "Partager mes informations de voyage",
    
          ctaNote: "Le formulaire privé est maintenant disponible plus bas.",
          vuelosImage: "vol_chr0ri",
          vuelosLabel: "Carte des vols",
          flightInfo: {
            eyebrow: "Mes informations de vol",
            title: "Dis-nous comment tu arrives",
            body:
              "Partage tes informations de vol pour que nous puissions organiser ton arrivée à Guadalajara et tes transferts. Tu peux enregistrer et modifier ces informations à tout moment.",
            originLabel: "Départ (origine)",
            originPlaceholder: "Recherche ton aéroport de départ…",
            destinationLabel: "Arrivée (destination)",
            destinationPlaceholder: "Recherche ton aéroport d’arrivée…",
            connectionsLabel: "Escales",
            connectionsHint: "Ajoute jusqu’à 3 aéroports d’escale (facultatif).",
            addConnection: "Ajouter une escale",
            removeConnection: "Retirer l’escale",
            arrivalDateLabel: "Date d’arrivée",
            arrivalTimeLabel: "Heure d’arrivée",
            finalFlightLabel: "Numéro du vol final",
            finalFlightPlaceholder: "Ex. AM 58",
            save: "Enregistrer mes informations de vol",
            saving: "Enregistrement…",
            saved: "Informations de vol enregistrées !",
            error: "Impossible d’enregistrer tes informations. Réessaie.",
            empty: "Tu n’as pas encore partagé tes informations de vol.",
            searchHint: "Écris le nom de la ville ou le code de l’aéroport.",
            noResults: "Aucun aéroport trouvé. Vérifie le nom ou le code.",
            departure: {
              eyebrow: "Mes informations de retour",
              title: "Dis-nous comment tu repars",
              body:
                "Partage tes informations de vol de retour pour que nous puissions organiser ton départ de Guadalajara et tes transferts. Tu peux enregistrer et modifier ces informations à tout moment.",
              originLabel: "Départ (origine)",
              originPlaceholder: "Recherche ton aéroport de départ…",
              destinationLabel: "Arrivée (destination)",
              destinationPlaceholder: "Recherche ton aéroport d’arrivée…",
              connectionsLabel: "Escales",
              connectionsHint: "Ajoute jusqu’à 3 aéroports d’escale (facultatif).",
              addConnection: "Ajouter une escale",
              removeConnection: "Retirer l’escale",
              departureDateLabel: "Date de départ",
              departureTimeLabel: "Heure de départ",
              finalFlightLabel: "Numéro du vol final",
              finalFlightPlaceholder: "Ex. AM 58",
              save: "Enregistrer mes informations de retour",
              saving: "Enregistrement…",
              saved: "Informations de retour enregistrées !",
              error: "Impossible d’enregistrer tes informations. Réessaie.",
              empty: "Tu n’as pas encore partagé tes informations de retour.",
              searchHint: "Écris le nom de la ville ou le code de l’aéroport.",
              noResults: "Aucun aéroport trouvé. Vérifie le nom ou le code.",
            },
          },
  },
  en: {
    
    
          eyebrow: "Coming from afar",
          title: "Your journey is part of the celebration too",
          body:
            "We will personally support everyone who wishes, travelling from Europe and beyond, with flights, arrival in Guadalajara, accommodation, and transfers.",
          points: [
            "Madrid–Guadalajara, operated by Aeromexico, is the priority direct connection from Europe.",
            "We will be delighted to help you organise your stay and your transfers.",
            "Don’t hesitate to contact us directly if you need advice on planning your trip and your stay in Mexico. We love sharing our tips about this country of a thousand facets!",
          ],
          routes: {
            eyebrow: "Journey map",
    
            title: "Getting to Roca Azul, then travelling on to the coast",
            note:
              "The times shown are indicative and can vary enormously. Please plan ahead and, even better, arrive early by booking accommodation if you can.",
            venue: "Roca Azul · Jocotepec",
            toVenueLabel: "GO TO ROCA AZUL",
            toBeachLabel: "GO TO THE BEACH",
    
            originsLabel: "To the wedding",
            destinationsLabel: "After the wedding",
            mapLabel: "Map of Roca Azul and its surroundings",
            directionsLabel: "Getting there (routes on Google Maps)",
            origins: [
              { place: "Central Guadalajara", duration: "≈ 1 hr 30", detail: "Toll-free route" },
    
              { place: "Our home · Tesistán", duration: "≈ 1 hr 45", detail: "Toll-free route" },
              { place: "GDL Airport", duration: "≈ 1 hr", detail: "Toll-free route" },
            ],
            destinations: [
              {
                place: "Barra de Navidad",
                duration: "≈ 5 hr",
                detail: "Toll-free · Cocula → Autlán → Barra",
              },
              {
                place: "Barra de Navidad",
                duration: "≈ 4 hr 45",
                detail: "Via Manzanillo · tolls ≈ MXN 500",
              },
              {
                place: "Manzanillo",
                duration: "≈ 4 hr 30",
                detail: "Tolls ≈ MXN 500",
              },
            ],
            maps: {
              venueLabel: "Getting to the venue",
              beachLabel: "Getting to the beach",
            },
          },
          cta: "Share my travel details",
    
          ctaNote: "The private form is now available below.",
          vuelosImage: "flights_ne6k2g",
          vuelosLabel: "Flight map",
          flightInfo: {
            eyebrow: "My flight details",
            title: "Tell us how you’re arriving",
            body:
              "Share your flight details so we can organise your arrival in Guadalajara and your transfers. You can save and update this information whenever you like.",
            originLabel: "Departure (origin)",
            originPlaceholder: "Search your departure airport…",
            destinationLabel: "Arrival (destination)",
            destinationPlaceholder: "Search your arrival airport…",
            connectionsLabel: "Connections",
            connectionsHint: "Add up to 3 connecting airports (optional).",
            addConnection: "Add a connection",
            removeConnection: "Remove connection",
            arrivalDateLabel: "Arrival date",
            arrivalTimeLabel: "Arrival time",
            finalFlightLabel: "Final flight number",
            finalFlightPlaceholder: "E.g. AM 58",
            save: "Save my flight details",
            saving: "Saving…",
            saved: "Flight details saved!",
            error: "We could not save your details. Please try again.",
            empty: "You haven’t shared your flight details yet.",
            searchHint: "Type the city name or the airport code.",
            noResults: "No airports found. Check the name or the code.",
            departure: {
              eyebrow: "My return flight details",
              title: "Tell us how you’re leaving",
              body:
                "Share your return flight details so we can organise your departure from Guadalajara and your transfers. You can save and update this information whenever you like.",
              originLabel: "Departure (origin)",
              originPlaceholder: "Search your departure airport…",
              destinationLabel: "Arrival (destination)",
              destinationPlaceholder: "Search your arrival airport…",
              connectionsLabel: "Connections",
              connectionsHint: "Add up to 3 connecting airports (optional).",
              addConnection: "Add a connection",
              removeConnection: "Remove connection",
              departureDateLabel: "Departure date",
              departureTimeLabel: "Departure time",
              finalFlightLabel: "Final flight number",
              finalFlightPlaceholder: "E.g. AM 58",
              save: "Save my return flight details",
              saving: "Saving…",
              saved: "Return flight details saved!",
              error: "We could not save your details. Please try again.",
              empty: "You haven’t shared your return flight details yet.",
              searchHint: "Type the city name or the airport code.",
              noResults: "No airports found. Check the name or the code.",
            },
          },
  },
};
