// Consolidate Firestore `guests` collection so each guest has exactly ONE
// document keyed by `firstName_lastName` (normalized), matching the `guest.id`
// generated by scripts/generate-guests.mjs from the CSV.
//
// Identity is matched by auth email (firebaseEmail), NOT by doc id. Contact
// details are stored at `guests/{guest.id}` where `guest.id` comes from
// guests.js. This script renames/merges docs so the doc id equals the
// name-based id, keeping contact storage consistent.
//
// Usage:
//   node scripts/rename-guests.mjs --dry-run     # preview only (default)
//   node scripts/rename-guests.mjs --execute     # apply the migration
import { initializeApp, cert } from "firebase-admin/app";
import { getFirestore } from "firebase-admin/firestore";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const serviceAccount = JSON.parse(
  readFileSync(join(__dirname, "../../../integraciones/google_sheets/service_account.json"), "utf8")
);

const app = initializeApp({ credential: cert(serviceAccount) });
const db = getFirestore(app);

const EXECUTE = process.argv.includes("--execute");

/** Normalize a name segment into a Firestore-safe id fragment. */
function slugify(part) {
  return String(part || "")
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-zA-Z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "")
    .toLowerCase();
}

/** Build the desired id from firstName + lastName. */
function desiredId(firstName, lastName) {
  const first = slugify(firstName);
  const last = slugify(lastName);
  if (first && last) return `${first}_${last}`;
  return first || last || "";
}

/** A doc is "rich" if it carries seed/contact data beyond just a name stub. */
function isRich(data) {
  const keys = Object.keys(data || {});
  return keys.some((k) =>
    ["row", "groupId", "cabinId", "phone", "email", "confirmed", "confirmedDate", "gender", "isChild", "invitationSent"].includes(k)
  );
}

// Special-case overrides: some docs must land on a specific id that differs
// from the naive name-based id, to match the app's guest.id in guests.js.
//   key: source doc id -> { target, name }
const OVERRIDES = {
  // Mónica Quezada: app guest.id is `monica_quezada`; doc 4 says "Moni Quezada".
  "4": { target: "monica_quezada", name: "Mónica Quezada" },
};

const snap = await db.collection("guests").get();
const docs = [];
snap.forEach((doc) => docs.push({ id: doc.id, data: doc.data() }));

// Compute target id for every doc.
const docTarget = new Map();
for (const d of docs) {
  if (OVERRIDES[d.id]) {
    docTarget.set(d.id, OVERRIDES[d.id].target);
  } else {
    docTarget.set(d.id, desiredId(d.data.firstName, d.data.lastName) || d.id);
  }
}

// Group docs by target id.
const byTarget = new Map();
for (const d of docs) {
  const target = docTarget.get(d.id);
  if (!byTarget.has(target)) byTarget.set(target, []);
  byTarget.get(target).push(d);
}

// Build the migration plan.
const plan = [];
for (const [target, group] of byTarget) {
  const rich = group.filter((d) => isRich(d.data));
  const thin = group.filter((d) => !isRich(d.data));

  if (group.length === 1 && group[0].id === target) {
    plan.push({ target, sources: group, action: "keep" });
    continue;
  }

  // Multiple rich docs with the same name are the SAME person only if they
  // share the same groupId (e.g. a numeric seed doc + a duplicate). If they
  // belong to different groups they are genuinely different people.
  const groups = new Set(rich.map((d) => d.data.groupId || d.data.group || "?"));
  const samePerson = groups.size <= 1;

  if (samePerson) {
    // One person (one rich doc, or duplicates sharing a group) + thin stubs.
    plan.push({ target, sources: group, action: "merge" });
  } else {
    // Multiple distinct people sharing a name -> keep separate.
    plan.push({ target, sources: group, action: "split" });
  }
}


// Report.
console.log(`Total documents: ${docs.length}`);
console.log(`Mode: ${EXECUTE ? "EXECUTE" : "DRY-RUN"}\n`);

let mergeCount = 0, splitCount = 0, keepCount = 0;
for (const p of plan) {
  if (p.action === "keep") { keepCount++; continue; }
  if (p.action === "merge") {
    mergeCount++;
    const names = p.sources.map((d) => `${d.id}${isRich(d.data) ? "(rich)" : "(thin)"}`).join(", ");
    console.log(`MERGE -> ${p.target.padEnd(28)} | ${names}`);
  } else {
    splitCount++;
    const names = p.sources.map((d) => `${d.id}(${d.data.groupId || d.data.group || "?"})`).join(", ");
    console.log(`SPLIT -> ${p.target.padEnd(28)} | ${names}`);
  }
}
console.log(`\nSummary: keep=${keepCount} merge=${mergeCount} split=${splitCount}`);

if (!EXECUTE) {
  console.log("\nDry-run complete. Re-run with --execute to apply.");
  process.exit(0);
}

// Execute.
console.log("\nApplying migration…");
const batchSize = 400;
let batch = db.batch();
let ops = 0;

for (const p of plan) {
  if (p.action === "keep") continue;

  if (p.action === "merge") {
    // Merge all source docs into target, preferring non-empty values.
    const merged = {};
    for (const d of p.sources) {
      for (const [k, v] of Object.entries(d.data)) {
        if (v !== undefined && v !== null && v !== "" && merged[k] === undefined) {
          merged[k] = v;
        }
      }
    }
    // Apply override name if present.
    const ov = OVERRIDES[p.sources.find((d) => OVERRIDES[d.id])?.id];
    if (ov) {
      const [fn, ...ln] = ov.name.split(" ");
      merged.firstName = fn;
      merged.lastName = ln.join(" ");
    }
    merged.firstName = merged.firstName ?? "";
    merged.lastName = merged.lastName ?? "";
    merged.guestId = p.target;
    batch.set(db.collection("guests").doc(p.target), merged);
    for (const d of p.sources) {
      if (d.id !== p.target) batch.delete(db.collection("guests").doc(d.id));
    }
    ops += 1 + p.sources.filter((d) => d.id !== p.target).length;
  } else {
    // Split: genuinely different people sharing a name. Keep thin stubs at
    // their current id (they are the app's guest.id reference) and give each
    // rich doc a unique suffixed id.
    let suffix = 1;
    for (const d of p.sources) {
      if (!isRich(d.data)) {
        // Thin stub: keep as-is (already the app's guest.id).
        batch.set(db.collection("guests").doc(d.id), { ...d.data, guestId: d.id });
        ops += 1;
        continue;
      }
      const newId = `${p.target}_${suffix++}`;
      batch.set(db.collection("guests").doc(newId), { ...d.data, guestId: newId });
      if (d.id !== newId) batch.delete(db.collection("guests").doc(d.id));
      ops += 2;
    }
  }


  if (ops >= batchSize) {
    await batch.commit();
    batch = db.batch();
    ops = 0;
  }
}
if (ops > 0) await batch.commit();
console.log("Done.");
process.exit(0);
