/**
 * thanksRepository — the ONLY module that touches the Firestore `thanks`
 * collection for the dashboard.
 *
 * Responsibilities (per the architecture contract):
 *   - collection paths (via `collections.thanks` from the shared contract)
 *   - Firestore queries / document refs
 *   - create / read / update / delete operations
 *   - Firestore-specific errors
 *
 * It contains NO UI behavior and NO business rules. The dashboard's live
 * `onSnapshot` listener for thanks is a subscription concern owned by the
 * dashboard bootstrap; this repository owns the WRITE path so presentation
 * code never calls `setDoc`/`deleteDoc` directly.
 *
 * Each `thanks` document carries a `guest` field (the guest ID) plus localized
 * thank-you messages (`es`, `fr`, `en`). The Firestore rules allow any
 * authenticated user to create/update and only admins to delete.
 */

import { doc, setDoc, deleteDoc, collection } from "firebase/firestore";
import { db } from "../firebase.js";
import { collections } from "../../../shared/firestore-paths.js";

/**
 * Create a new thanks document. The doc id is auto-generated by Firestore.
 * At least one of `es` / `fr` / `en` must be a non-empty string (validated by
 * the caller); the payload only includes the languages that were provided.
 *
 * @param {object} payload — `{ guest, es?, fr?, en? }` (guest id + localized text).
 * @returns {Promise<void>}
 */
export async function createThanks(payload) {
  const data = {
    guest: String(payload.guest || "").trim(),
  };
  ["es", "fr", "en"].forEach((lang) => {
    const value = String(payload[lang] || "").trim();
    if (value) data[lang] = value;
  });
  await setDoc(doc(collection(db, collections.thanks)), data);
}

/**
 * Merge-write the localized text fields onto an existing thanks document.
 * Only the provided languages are written; missing ones are left untouched.
 *
 * @param {string} creditId — the thanks document id.
 * @param {object} payload — `{ guest?, es?, fr?, en? }`.
 * @returns {Promise<void>}
 */
export async function updateThanks(creditId, payload) {
  const data = {};
  if (payload.guest !== undefined) data.guest = String(payload.guest || "").trim();
  ["es", "fr", "en"].forEach((lang) => {
    if (payload[lang] !== undefined) data[lang] = String(payload[lang] || "").trim();
  });
  await setDoc(doc(db, collections.thanks, creditId), data, { merge: true });
}

/**
 * Delete a thanks document.
 * @param {string} creditId — the thanks document id.
 * @returns {Promise<void>}
 */
export async function deleteThanks(creditId) {
  await deleteDoc(doc(db, collections.thanks, creditId));
}
